//
//  NerdCam.swift
//  Challenge
//
//  Created by Mike, Tyler, Tanner on 03/12/2015.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class KennyHat : NSObject {

    //// Cache

    private struct Cache {
        static let fillColorGreen: UIColor = UIColor(red: 0.494, green: 0.826, blue: 0.130, alpha: 1.000)
        static let fillRedColor: UIColor = UIColor(red: 0.816, green: 0.008, blue: 0.106, alpha: 1.000)
    }

    //// Colors

    public class var fillColorGreen: UIColor { return Cache.fillColorGreen }
    public class var fillRedColor: UIColor { return Cache.fillRedColor }

    //// Drawing Methods

    public class func drawEyeLeft(variableColor variableColor: UIColor = UIColor(red: 0.295, green: 0.569, blue: 0.547, alpha: 1.000), ourRect: CGRect = CGRectMake(0, 0, 52, 38)) {

        //// Frames
        let frame = CGRectMake(ourRect.origin.x, ourRect.origin.y, ourRect.size.width, ourRect.size.height)


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.78763 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.17631 * frame.width, frame.minY + 0.51095 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.27994 * frame.width, frame.minY + 0.78763 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.18044 * frame.width, frame.minY + 0.52224 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.17631 * frame.width, frame.minY + 0.48905 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.17379 * frame.width, frame.minY + 0.50405 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.17379 * frame.width, frame.minY + 0.49595 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.21237 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.18044 * frame.width, frame.minY + 0.47776 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.27994 * frame.width, frame.minY + 0.21237 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.82369 * frame.width, frame.minY + 0.48905 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72006 * frame.width, frame.minY + 0.21237 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.81956 * frame.width, frame.minY + 0.47776 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.82369 * frame.width, frame.minY + 0.51095 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.82621 * frame.width, frame.minY + 0.49595 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.82621 * frame.width, frame.minY + 0.50405 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.78763 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.81956 * frame.width, frame.minY + 0.52224 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.72006 * frame.width, frame.minY + 0.78763 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.78763 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.21279 * frame.width, frame.minY + 0.50000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.73868 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.23356 * frame.width, frame.minY + 0.54824 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.32656 * frame.width, frame.minY + 0.73868 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.78721 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67344 * frame.width, frame.minY + 0.73868 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76644 * frame.width, frame.minY + 0.54824 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.26132 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76644 * frame.width, frame.minY + 0.45176 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67344 * frame.width, frame.minY + 0.26132 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.21279 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.32656 * frame.width, frame.minY + 0.26132 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.23356 * frame.width, frame.minY + 0.45176 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.21279 * frame.width, frame.minY + 0.50000 * frame.height))
        bezierPath.closePath()
        bezierPath.usesEvenOddFillRule = true;

        variableColor.setFill()
        bezierPath.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.62974 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.40519 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.44771 * frame.width, frame.minY + 0.62974 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.40519 * frame.width, frame.minY + 0.57153 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.42308 * frame.width, frame.minY + 0.47553 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.40519 * frame.width, frame.minY + 0.48647 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.41319 * frame.width, frame.minY + 0.47553 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.44096 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.43296 * frame.width, frame.minY + 0.47553 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.44096 * frame.width, frame.minY + 0.48647 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.58079 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.44096 * frame.width, frame.minY + 0.54455 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46746 * frame.width, frame.minY + 0.58079 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.55904 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.53254 * frame.width, frame.minY + 0.58079 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.55904 * frame.width, frame.minY + 0.54455 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.41921 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55904 * frame.width, frame.minY + 0.45545 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.53254 * frame.width, frame.minY + 0.41921 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.48212 * frame.width, frame.minY + 0.39474 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.49012 * frame.width, frame.minY + 0.41921 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.48212 * frame.width, frame.minY + 0.40826 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.37026 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48212 * frame.width, frame.minY + 0.38121 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.49012 * frame.width, frame.minY + 0.37026 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.59481 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55229 * frame.width, frame.minY + 0.37026 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.59481 * frame.width, frame.minY + 0.42847 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.62974 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59481 * frame.width, frame.minY + 0.57153 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.55229 * frame.width, frame.minY + 0.62974 * frame.height))
        bezier3Path.closePath()
        bezier3Path.usesEvenOddFillRule = true;

        variableColor.setFill()
        bezier3Path.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.73500 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.32827 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.40531 * frame.width, frame.minY + 0.73500 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.32827 * frame.width, frame.minY + 0.62958 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.26500 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.32827 * frame.width, frame.minY + 0.37042 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.40531 * frame.width, frame.minY + 0.26500 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.67173 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59469 * frame.width, frame.minY + 0.26500 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67173 * frame.width, frame.minY + 0.37042 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.73500 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67173 * frame.width, frame.minY + 0.62958 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.59469 * frame.width, frame.minY + 0.73500 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.73500 * frame.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.31395 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.36404 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.42504 * frame.width, frame.minY + 0.31395 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.36404 * frame.width, frame.minY + 0.39742 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.68605 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.36404 * frame.width, frame.minY + 0.60258 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.42504 * frame.width, frame.minY + 0.68605 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.63596 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.57496 * frame.width, frame.minY + 0.68605 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.63596 * frame.width, frame.minY + 0.60258 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.31395 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.63596 * frame.width, frame.minY + 0.39742 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.57496 * frame.width, frame.minY + 0.31395 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.31395 * frame.height))
        bezier2Path.closePath()
        bezier2Path.usesEvenOddFillRule = true;

        variableColor.setFill()
        bezier2Path.fill()
    }

    public class func drawEyeRight(variableColor variableColor: UIColor = UIColor(red: 0.295, green: 0.569, blue: 0.547, alpha: 1.000), ourRect: CGRect = CGRectMake(0, 0, 52, 38)) {

        //// Frames
        let frame = CGRectMake(ourRect.origin.x, ourRect.origin.y, ourRect.size.width, ourRect.size.height)


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.78763 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.17631 * frame.width, frame.minY + 0.51095 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.27994 * frame.width, frame.minY + 0.78763 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.18044 * frame.width, frame.minY + 0.52224 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.17631 * frame.width, frame.minY + 0.48905 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.17379 * frame.width, frame.minY + 0.50405 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.17379 * frame.width, frame.minY + 0.49595 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.21237 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.18044 * frame.width, frame.minY + 0.47776 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.27994 * frame.width, frame.minY + 0.21237 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.82369 * frame.width, frame.minY + 0.48905 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72006 * frame.width, frame.minY + 0.21237 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.81956 * frame.width, frame.minY + 0.47776 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.82369 * frame.width, frame.minY + 0.51095 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.82621 * frame.width, frame.minY + 0.49595 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.82621 * frame.width, frame.minY + 0.50405 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.78763 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.81956 * frame.width, frame.minY + 0.52224 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.72006 * frame.width, frame.minY + 0.78763 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.78763 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.21279 * frame.width, frame.minY + 0.50000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.73868 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.23356 * frame.width, frame.minY + 0.54824 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.32656 * frame.width, frame.minY + 0.73868 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.78721 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67344 * frame.width, frame.minY + 0.73868 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76644 * frame.width, frame.minY + 0.54824 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.26132 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.76644 * frame.width, frame.minY + 0.45176 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67344 * frame.width, frame.minY + 0.26132 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.21279 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.32656 * frame.width, frame.minY + 0.26132 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.23356 * frame.width, frame.minY + 0.45176 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.21279 * frame.width, frame.minY + 0.50000 * frame.height))
        bezierPath.closePath()
        bezierPath.usesEvenOddFillRule = true;

        variableColor.setFill()
        bezierPath.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.62974 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.40519 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.44771 * frame.width, frame.minY + 0.62974 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.40519 * frame.width, frame.minY + 0.57153 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.42308 * frame.width, frame.minY + 0.47553 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.40519 * frame.width, frame.minY + 0.48647 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.41319 * frame.width, frame.minY + 0.47553 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.44096 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.43296 * frame.width, frame.minY + 0.47553 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.44096 * frame.width, frame.minY + 0.48647 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.58079 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.44096 * frame.width, frame.minY + 0.54455 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.46746 * frame.width, frame.minY + 0.58079 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.55904 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.53254 * frame.width, frame.minY + 0.58079 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.55904 * frame.width, frame.minY + 0.54455 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.41921 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55904 * frame.width, frame.minY + 0.45545 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.53254 * frame.width, frame.minY + 0.41921 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.48212 * frame.width, frame.minY + 0.39474 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.49012 * frame.width, frame.minY + 0.41921 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.48212 * frame.width, frame.minY + 0.40826 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.37026 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.48212 * frame.width, frame.minY + 0.38121 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.49012 * frame.width, frame.minY + 0.37026 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.59481 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55229 * frame.width, frame.minY + 0.37026 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.59481 * frame.width, frame.minY + 0.42847 * frame.height))
        bezier3Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.62974 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59481 * frame.width, frame.minY + 0.57153 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.55229 * frame.width, frame.minY + 0.62974 * frame.height))
        bezier3Path.closePath()
        bezier3Path.usesEvenOddFillRule = true;

        variableColor.setFill()
        bezier3Path.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.73500 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.32827 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.40531 * frame.width, frame.minY + 0.73500 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.32827 * frame.width, frame.minY + 0.62958 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.26500 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.32827 * frame.width, frame.minY + 0.37042 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.40531 * frame.width, frame.minY + 0.26500 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.67173 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.59469 * frame.width, frame.minY + 0.26500 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.67173 * frame.width, frame.minY + 0.37042 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.73500 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.67173 * frame.width, frame.minY + 0.62958 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.59469 * frame.width, frame.minY + 0.73500 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.73500 * frame.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.31395 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.36404 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.42504 * frame.width, frame.minY + 0.31395 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.36404 * frame.width, frame.minY + 0.39742 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.68605 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.36404 * frame.width, frame.minY + 0.60258 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.42504 * frame.width, frame.minY + 0.68605 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.63596 * frame.width, frame.minY + 0.50000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.57496 * frame.width, frame.minY + 0.68605 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.63596 * frame.width, frame.minY + 0.60258 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.31395 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.63596 * frame.width, frame.minY + 0.39742 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.57496 * frame.width, frame.minY + 0.31395 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.31395 * frame.height))
        bezier2Path.closePath()
        bezier2Path.usesEvenOddFillRule = true;

        variableColor.setFill()
        bezier2Path.fill()
    }

    //// Generated Images

    public class func imageOfEyeRight(variableColor variableColor: UIColor = UIColor(red: 0.295, green: 0.569, blue: 0.547, alpha: 1.000), ourRect: CGRect = CGRectMake(0, 0, 52, 38)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(52, 38), false, 0)
            KennyHat.drawEyeRight(variableColor: variableColor, ourRect: ourRect)

        let imageOfEyeRight = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfEyeRight
    }

}
